import static org.junit.jupiter.api.Assertions.*;

import org.junit.Test;

class PilhaTestException {

	Pilha pilha;
	
	@Test
	void testeInserirLivroException() {
		pilha = new Pilha();
		try {
			pilha.inserindoLivroNaPilhaComException(new Livro("O Pedro"));
		} catch (RuntimeException e) {
			assertTrue(true);
		}
		
	}
	@org.junit.Test(expected = RuntimeException.class)
	void testeInserirLivroException2() {
		pilha = new Pilha();
		pilha.inserindoLivroNaPilhaComException(new Livro("O Pedro"));
		
	}
	

}
